import { StatusBar } from 'react-native';
import { StyleSheet,Text,TouchableOpacity,View } from 'react-native';

export default function App(){
    return(
        <View>
            <Text>ENTRAR</Text>
            <Text>LEMBRAR MEU E-MAIL</Text>
            <TEXT>SENHA</TEXT>
            <TouchableOpacity>
                <TEXT>ESQUECI MINHA SENHA</TEXT>
            </TouchableOpacity>
            <TouchableOpacity>
                <TEXT>ENTRAR</TEXT>
            </TouchableOpacity>
        </View>
    )
}